// <auto-generated />
using System;
using Dal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(DatabaseManager))]
    partial class DatabaseManagerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dal.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Customer__3214EC0732B98CB9");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Dal.Models.Dishes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asado")
                        .HasColumnType("bit");

                    b.Property<bool>("Beets")
                        .HasColumnType("bit");

                    b.Property<bool>("Buns")
                        .HasColumnType("bit");

                    b.Property<bool>("Cabbage")
                        .HasColumnType("bit");

                    b.Property<bool>("Carrots")
                        .HasColumnType("bit");

                    b.Property<bool>("Chicken")
                        .HasColumnType("bit");

                    b.Property<bool>("Chicken_Breast")
                        .HasColumnType("bit");

                    b.Property<bool>("Chicken_Home_Fries")
                        .HasColumnType("bit");

                    b.Property<bool>("Confited_Garlic")
                        .HasColumnType("bit");

                    b.Property<bool>("Eggplant")
                        .HasColumnType("bit");

                    b.Property<bool>("Entrecote_Steak")
                        .HasColumnType("bit");

                    b.Property<bool>("Fruit_smoothie")
                        .HasColumnType("bit");

                    b.Property<bool>("Grilled_fish")
                        .HasColumnType("bit");

                    b.Property<bool>("Hummus")
                        .HasColumnType("bit");

                    b.Property<bool>("Ice_cream")
                        .HasColumnType("bit");

                    b.Property<bool>("Khohlrabi")
                        .HasColumnType("bit");

                    b.Property<bool>("Lettuce")
                        .HasColumnType("bit");

                    b.Property<bool>("Matbuchah")
                        .HasColumnType("bit");

                    b.Property<bool>("Potato_borax")
                        .HasColumnType("bit");

                    b.Property<bool>("Salmon_fish")
                        .HasColumnType("bit");

                    b.Property<bool>("Schnitzel")
                        .HasColumnType("bit");

                    b.Property<bool>("Soufflé")
                        .HasColumnType("bit");

                    b.Property<bool>("Spicy_Eggplant")
                        .HasColumnType("bit");

                    b.Property<bool>("Sweet_Potatoes")
                        .HasColumnType("bit");

                    b.Property<bool>("Tomatoes")
                        .HasColumnType("bit");

                    b.Property<bool>("Vegetable_stuffed_tortilla")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_Dishes");

                    b.ToTable("Dishes", (string)null);
                });

            modelBuilder.Entity("Dal.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountOfDishes")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("InEvening")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWaiters")
                        .HasColumnType("int");

                    b.Property<int?>("SecretaryId")
                        .HasColumnType("int")
                        .HasColumnName("secretaryId");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC072C1FDC76");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MenuId");

                    b.ToTable("Invitation", (string)null);
                });

            modelBuilder.Entity("Dal.Models.Menus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TypeOfDish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC07EFD41596");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("Dal.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bonus")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HoursAtWeek")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int?>("Seniority")
                        .HasColumnType("int");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Worker__3214EC07C0EBE5E7");

                    b.ToTable("Worker", (string)null);
                });

            modelBuilder.Entity("Dal.Models.Invitation", b =>
                {
                    b.HasOne("Dal.Models.Customer", "Customer")
                        .WithMany("Invitations")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Invitation_ToTable");

                    b.HasOne("Dal.Models.Dishes", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Dal.Models.Customer", b =>
                {
                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
